Fix install
mviewer/mviewerstudio pull request #168
Opened 2023-02-09 11:04 UTC by Gaetanbrl

2023-02-09 11:05 UTC, Gaetanbrl commented
@spelhate je vois qu'à l'install on a des sous répertoires `store/store/store/store...` comme ss une boucle les avait générés.

Ils ne sont pas recréée si on les supprime.

2023-02-10 09:12 UTC, spelhate commented on srv/python/requirements.txt
> +requests
Pourquoi ce requirement supplémentaire ?

2023-02-10 09:14 UTC, Gaetanbrl commented on srv/python/requirements.txt
> +requests
c'est une dépendance manquante qui bloquait l'install chez moi, pour moi c'était compris dans la version de python mais apparemment pas toujours...

2023-02-10 10:54 UTC, Gaetanbrl commented
@spelhate modifications du script (index.html manquant) + doc apportée.

2023-02-22 14:47 UTC, Gaetanbrl commented
Je viens de refaire une install branche develop : 

1. récupérer le fichier
2. lancer la commande 
sh install_backend.sh /home/gaetan/git develop

3. créer le lien symbolique 

ln -s /home/gaetan/git/mviewerstudio/srv/python/mviewer_backend/store /home/gaetan/git/mviewer/apps/store_dev

4. Adapter la config front

`nano /home/gaetan/git/mviewerstudio/srv/python/mviewerstudio_backend/static/apps/config.json`

Changer les valeurs pour pointer vers `store_dev `(nom de mon dossier dans `mviewer/apps`):


```
        "mviewer_instance": "http://localhost:5051/",
        "conf_path_from_mviewer": "apps/store_dev/",
        "mviewer_short_url": {
            "used": true,
            "apps_folder": "store_dev"
        },
```

5. Adapter la config backend
- CONF_PATH_FROM_MVIEWER
- EXPORT_CONF_FOLDER 

```
class Config:
    CONF_PATH_FROM_MVIEWER = os.getenv("CONF_PATH_FROM_MVIEWER", "apps/store_dev/")
    EXPORT_CONF_FOLDER = os.getenv("EXPORT_CONF_FOLDER", "./store")
    LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
    PROXY_WHITE_LIST = ['geobretagne.fr', 'ows.region-bretagne.fr']
```

6. Démarrer le serveur flask 

```
cd mviewerstudio/srv/python
source .venv/bin/activate
cd mviewerstudio_backend
flask run
```

Tout fonctionne.

> Note:
> avec mviewer lancé via `npm start` j'ai une erreur CORS
> il faut lancer mviewer avec `npm run start --cors`

2023-02-23 08:41 UTC, lecault commented
Je viens de tester à partir de cette page : https://github.com/jdev-org/mviewerstudio/blob/develop/docs/doc_tech/install_python.rst

ça fonctionne, voici mes remarques sur la doc le script étant OK.

### Organisation globale de la page

Dans la partie installation j'ajouterai un 5. Lancer mviewerstudio en mode développement (déplacement de la partie Serveur de développement).
Il y a une coquille "**Mttre** en production mviewerstudio"

###Corrections
Lien /srv/python/mviewerstudio_backend/apps/static/config.json à corriger (manque le static)
	"mviewer_instance": "http://localhost/mviewer/",
Enlever les store_dev :
"conf_path_from_mviewer": "apps/store/",
CONF_PATH_FROM_MVIEWER = os.getenv("CONF_PATH_FROM_MVIEWER", "apps/store/")
Ajout à la fin de l'url pour ouvrir mviewerstudio http://localhost:5000/

Je peux les corriger à postériori si plus simple

2023-02-23 08:48 UTC, Gaetanbrl commented
> Dans la partie installation j'ajouterai un 5

Je pense qu'il ne faut pas rajouter de 5, c'était le cas dans la version avant mes modifications et pour moi ca n'aide pas à savoir ce qui est obligatoire juste pour mettre en prod sans faire de dev.

Il faut distinguer 3 sections donc : 

1. L'installation des sources -> Section `Installation`

Après l'installation, soit on met en prod, soit on fait du dev.

2. Environnement de développement

Seulement si on est intéressé par faire du dev, on utilise le serveur de développement.

3. Mettre en production

On install + mettre en prod -> Serveur de dev inutile.

2023-02-23 08:55 UTC, Gaetanbrl commented
Les modifs sont appliquées @lecault

2023-02-23 10:50 UTC, lecault commented
Ok ça me va, il faut juste préciser à la fin de la partie installation que soit on choisit la mise en prod ou l'utilisation en dev.

PR ok je compléterai après

2023-02-23 12:58 UTC, Gaetanbrl commented
> Ok ça me va, il faut juste préciser à la fin de la partie installation que soit on choisit la mise en prod ou l'utilisation en dev.

j'ai rajouté une note.

2023-02-27 12:57 UTC, spelhate commented
@lecault @Gaetanbrl  Est ce qu'on peut valider cette PR dès maintenant ou bien faut-il renseigner la partie mise en production ? Je peux m'en occuper mais pas avant la fin de semaine.

2023-02-27 13:05 UTC, Gaetanbrl commented
>  ou bien faut-il renseigner la partie mise en production

Pour moi c'est à compléter après vu qu'on avait pas grand chose déjà...

2023-02-27 13:10 UTC, spelhate commented
> > ou bien faut-il renseigner la partie mise en production
> 
> Pour moi c'est à compléter après vu qu'on avait pas grand chose déjà...

Ok.

2023-02-27 13:11 UTC, Gaetanbrl commented
> copie du fichier exemple
> 7. Adapter la config front

@spelhate  Où vois-tu cette étape 7 ?

2023-02-27 13:16 UTC, Gaetanbrl commented
@spelhate où vois-tu cette doc avec les étapes ??

2023-02-27 13:21 UTC, spelhate commented
> @spelhate où vois-tu cette doc avec les étapes ??

Dans ton commentaire de cette PR d'il y a 5 jours

2023-02-27 13:26 UTC, Gaetanbrl commented
> Dans ton commentaire de cette PR d'il y a 5 jours

Aaah ! :) 
C'était juste un test pour valider le process, ce n'est pas la doc.
 
Voici la doc revue avec Loic : 

https://github.com/jdev-org/mviewerstudio/tree/develop/docs/doc_tech

2023-02-27 13:40 UTC, spelhate commented
> > Dans ton commentaire de cette PR d'il y a 5 jours
> 
> Aaah ! :) C'était juste un test pour valider le process, ce n'est pas la doc.
> 
> Voici la doc revue avec Loic :
> 
> https://github.com/jdev-org/mviewerstudio/tree/develop/docs/doc_tech

 Ok. mais je pense qu'on peut supprimer cette partie : 


2. Ajouter un lien symbolique entre mviewer et mviewerstudio

Cette étape permet de prévisualiser les cartes réalisées dans mviewerstudio via un mviewer disponible.

    Mviewerstudio sauvegarde les dans mviewerstudio/srv/python/mviewer_backend/store
    Mviewer lira les cartes dans mviewer/apps/store qui pointera en réalité vers le /store mviewerstudio

ln -s /<full_path>/mviewerstudio/srv/python/mviewerstudio_backend/store /<full_path>/mviewer/apps/store


A la condition de démarrer le backend Python avec la variable d'environnement EXPORT_CONF_FOLDER bien renseignée

Dans mon cas, en dev je fais 
`EXPORT_CONF_FOLDER=/home/debian/mviewer/apps/store/ && flask run`
à la place de 
`flask run`

et en prod dans mon fichier mviewerstrudio.service j'ai :

```
[Service]
User=debian
Environment="EXPORT_CONF_FOLDER=/home/debian/mviewer/apps/store/"
WorkingDirectory=/home/debian/mviewerstudio/srv/python
ExecStart=/home/debian/mviewerstudio/venv/bin/gunicorn -b 127.0.0.1:5007 mviewerstudio_backend.app:app
```

2023-02-27 13:45 UTC, Gaetanbrl commented
> mais je pense qu'on peut supprimer cette partie

A discuter en COTECH pour valider car je commence a être perdu entre la validation de la méthode documentée et l'optimisation via une méthode alternative (demain au plus tard si possible -> Top priorité).

2023-02-27 14:42 UTC, spelhate commented
> 

Ca marche.

2023-02-27 15:26 UTC, spelhate requested changes

2023-02-27 15:26 UTC, spelhate commented on docs/doc_tech/install_python.rst
> +(Attention : le paramètre ``mviewer_instance`` doit commencer par ``http`` et finir par ``/``)
Pour info, ça marche aussi avec une URL relative exemple : /mviewer/

2023-02-27 15:26 UTC, spelhate commented on srv/python/install_backend_python.sh
> +    git clone https://github.com/jdev-org/mviewerstudio.git
Ca pointe sur le dépôt jdev. C'est normal ?

2023-02-27 15:26 UTC, spelhate commented on docs/doc_tech/install_python.rst
> +Mettre en production mviewerstudio
Je documenterai cette partie d'ici la semaine prochaine dans le cadre d'une nouvelle PR.

2023-02-27 15:26 UTC, spelhate commented on docs/doc_tech/install_python.rst
> +
La configuration peut également être définie via des variables d'environnement pour les paramètres : 
CONF_PATH_FROM_MVIEWER  ( défault = apps/store/)
EXPORT_CONF_FOLDER  ( défault = ./store/)

exemple :
```sh
export CONF_PATH_FROM_MVIEWER=apps/store_test/
export EXPORT_CONF_FOLDER=/var/www/mviewer/apps/store-test/         (*)
flask run
```

(*) Vérifier au préalable que le répertoire existe et que le user démarrant flask a les droits sur ce dossier

2023-02-27 15:39 UTC, spelhate commented on docs/doc_tech/install_python.rst
> +**4. Ouvrir la configuration backend ``/srv/python/mviewerstudio_backend/settings.py`` et adapter les paramètres**
Plutôt que de modifier ce fichier, il faut définir les variables d'environnement correspondantes avant de lancer Flask.

```sh
export CONF_PATH_FROM_MVIEWER=apps/store_test/
export EXPORT_CONF_FOLDER=/var/www/mviewer/apps/store-test/
flask run
```

2023-02-27 16:08 UTC, spelhate commented
Je viens de tester le script.
En n'étant pas root, l'install des packages ne passe pas. Je pense qu'il faut ajouter 2 sudo dans les lignes de commande.
Ensuite je lance l'application via un service que j'ai créé et que je vais partager (Le service définit l'emplacement du dossier store), du coup pas besoin de faire de lien symbolique.

Conclusion ça marche. Merci @Gaetanbrl 

Et pour une mise à jour de l'application on peut rejouer directement le script ? ou bien il faut supprimer le clone et relancer le script ?

2023-02-27 16:18 UTC, spelhate commented
A discuter lors du prochain COTECH : l'utilisation de la lib `python-dotenv` pour gérer les **variables** du backend dans un fichier .**env**

2023-02-27 16:32 UTC, Gaetanbrl commented on srv/python/install_backend_python.sh
> +    git clone https://github.com/jdev-org/mviewerstudio.git
non c'est une coquille

2023-02-27 16:36 UTC, Gaetanbrl commented on docs/doc_tech/install_python.rst
> +(Attention : le paramètre ``mviewer_instance`` doit commencer par ``http`` et finir par ``/``)
ok je supprime la référence au http

2023-02-27 16:45 UTC, Gaetanbrl commented on docs/doc_tech/install_python.rst
> +
je viens de rajouter ce détail dans la doc.

2023-02-27 16:47 UTC, Gaetanbrl commented on docs/doc_tech/install_python.rst
> +**4. Ouvrir la configuration backend ``/srv/python/mviewerstudio_backend/settings.py`` et adapter les paramètres**
Ce point est précisé dans la section `configuration` :

https://github.com/jdev-org/mviewerstudio/blob/develop/docs/doc_tech/install_python.rst#configuration

2023-02-27 16:55 UTC, Gaetanbrl commented
> En n'étant pas root, l'install des packages ne passe pas.

Est-ce qu'il ne faudrait pas juste lancer le script en sudo ?

Pour moi c'était un prérequis (le même qu'avant) -> Avoir les droits d'install (idem pour python).

... une phrase est peut être à préciser dans la doc.

2023-02-28 15:19 UTC, Gaetanbrl commented
Validée : vu en cotech avec @lecault et @spelhate le 28/02/2023 - 16h05

2023-02-28 15:19 UTC, merged