[Issue-148] Arborescence du mviewer dans le panneau des thématiques
mviewer/mviewerstudio pull request #324
Opened 2024-11-07 13:49 UTC by LPoin

Modifie l'arborescence des Thèmatiques & Données pour supprimer la modale de création et modification des thèmes et couches.
- Gestion par ID et non plus par élément actif
- Refacto du code concerné

2024-11-08 08:22 UTC, lecault commented
Merci, les tests sont réalisés ici : https://kartenn.region-bretagne.fr/mviewerstudio-dev/index.html#

- Je n'arrive pas à récupérer les pictos des thématiques : 
![image](https://github.com/user-attachments/assets/d90cc302-dc50-4260-b52b-eed8f2219368)

- L'option déroulé par défaut n'est pas pris en compte si on ne clique pas sur enregistrer
- La modification du nom de la thématique n'est pas pris en compte si on ne clique pas sur enregistrer
- Le retour à la ligne est autorisé dans le nommage de la thématique ce qui ne devrait pas être le cas
![image](https://github.com/user-attachments/assets/b2f24894-d086-4424-b247-9ad90f637426)
- Ok pour le rafraîchissement du nom des couches
- Comme dit dans l'autre issue, je n'ai pas tenu compte des drap and drop

2024-11-08 08:40 UTC, Gaetanbrl commented
> L'option déroulé par défaut n'est pas pris en compte si on ne clique pas sur enregistrer
> La modification du nom de la thématique n'est pas pris en compte si on ne clique pas sur enregistrer

Ce sont des remarques pour modification ou des questions ?

En l'état je trouve ça normal de ne pas enregistrer à chaque modification. L'utilisateur devrait faire ses modifications et sauvegarder quand il le souhaite à la fin ou bien annuler ses modifications.
Si on sauvegarde à chaque modification, il faut que l'utilisateur identifie la version avant ses modifications (ca en fera une liste...) et la sélectionne comme version courante.

Je ne suis pas certain que ca facilite ce cas d'usage.

2024-11-08 08:49 UTC, Gaetanbrl requested changes
Après un petit nettoyage à faire  (code commenté / console.log) ce sera bon pour le coté code.

2024-11-08 08:49 UTC, Gaetanbrl commented on js/mviewerstudio.js
> +                    <span class="theme-name moveList" contentEditable="true">${title}</span><span class="theme-infos-layer">Ext.</span>
Est-ce qu'un Input ne serait pas plus simple à gérer qu'un [contentEditable](https://developer.mozilla.org/fr/docs/Web/HTML/Global_attributes/contenteditable) peut-être un peu trop permissif ?

2024-11-08 09:26 UTC, lecault commented
> > L'option déroulé par défaut n'est pas pris en compte si on ne clique pas sur enregistrer
> > La modification du nom de la thématique n'est pas pris en compte si on ne clique pas sur enregistrer
> 
> Ce sont des remarques pour modification ou des questions ?
> 
> En l'état je trouve ça normal de ne pas enregistrer à chaque modification. L'utilisateur devrait faire ses modifications et sauvegarder quand il le souhaite à la fin ou bien annuler ses modifications. Si on sauvegarde à chaque modification, il faut que l'utilisateur identifie la version avant ses modifications (ca en fera une liste...) et la sélectionne comme version courante.
> 
> Je ne suis pas certain que ca facilite ce cas d'usage.

On a discuté avec Stéphane. 
Sur la version précédente, la modal thématique enregistrait automatiquement les modifications sans cliquer sur enregistrer, c'est pour cela qu'on est perturbé par ce nouveau fonctionnement.

Notre idée : le clic sur preview enregistre le projet s'il y a des modifications et ne l'enregistre pas s'il n'y a pas de modifications.
Qu'en pensez vous ?
![image](https://github.com/user-attachments/assets/e3df152e-f046-4e1e-b10e-6b2cd04d57b9)

![image](https://github.com/user-attachments/assets/775abbcd-002e-4e0d-aa6f-95914911308f)

2024-11-08 09:27 UTC, lecault commented
Choisir ce picto par défaut pour les thématiques : 

![image](https://github.com/user-attachments/assets/f2f6ff8f-1843-4aeb-9b8b-69bca35830e3)

2024-11-08 09:47 UTC, Gaetanbrl commented
> Notre idée : le clic sur preview enregistre le projet s'il y a des modifications et ne l'enregistre pas s'il n'y a pas de modifications.
Qu'en pensez vous ?

Soit on reste sur le fonctionnement initial soit on fait une nouvelle évolution.

2024-11-08 09:48 UTC, Gaetanbrl commented
> Choisir ce picto par défaut pour les thématiques :

Tu es certain que c'est le plus adapté ?

2024-11-13 08:40 UTC, LPoin commented
Push  des modifs selon les retours de PR.

2024-11-13 09:35 UTC, lecault commented
Merci pour les modifications : 
- OK pour la sauvegarde via clic sur preview
- Zone de modification du titre plus lisible
- Reste à modifier le picto par défaut

2024-11-22 10:42 UTC, Gaetanbrl commented
> Reste à modifier le picto par défaut

Ok on merge une fois cette modification faite.
Merci @LPoin @lecault

2024-11-22 14:10 UTC, Gaetanbrl approved these changes

2024-11-22 14:10 UTC, Gaetanbrl commented
@lecault je te laisse faire le squash and merge si c'est bon pour toi

2024-11-22 15:08 UTC, merged