[Issue-294] Ajout du niveau groupe dans l'arborescence
mviewer/mviewerstudio pull request #330
Opened 2024-11-22 08:25 UTC by LPoin

Ajoute le niveau groupe dans l'arborescence des thèmes.
- Modifie l'arborescence
- Ajoute le drag'n'drop niveau thèmes / groupes / layers
- Montée de version de Sortable.js
!!! A merger après https://github.com/mviewer/mviewerstudio/pull/324 !!!

Elements à modifier / corriger pour validation de cette PR : 

- [x] Bug chargement mviewer avec des groupes sans couche
- [x] Bug lorsqu'on bouge la seule couche d'un groupe en dehors d'un groupe
- [x] Remplacer l'attribut `title` par `name` pour les groupes
- [x] Vérifier / corriger le problème de drag & drop vu dans [ce commentaire](https://github.com/mviewer/mviewerstudio/pull/330#issuecomment-2494137332) plus bas
- [x] Au niveau des boutons, il faudrait modifier le label pour avoir « + Ajouter un groupe », « + Ajouter une donnée », « + Ajouter une thématique »
- [x] La div « Données » (anciennement « Couches ») reste visible tout le temps et accueillera toutes les données qui ne sont pas dans un groupe
- [x] La div « Groupes » doit être visible que si on a un ou plusieurs groupe
- [x] Remplacer « Couches » par « Données »
- [x] Problème de visibilité de la données suite à un drag&drop vers un groupe
- [x] Récupération des infos d'une donnée lors du clique sur "paramétrer la donnée"
- [x] Scintillement au drag & drop après avoir publié une carte (@Gaetanbrl)
- [x] issue #344 (@Gaetanbrl)
- [x] issue #341 (@Gaetanbrl)
- [x] issue #342 (@LPoin)

Eléments facultatifs :

- [ ] (Facultatif - Si dans les délais) Après tests et manipulations, il est demandé si on peut rajouter un bouton « Ajouter une donnée » au niveau de chaque groupe pour ajouter directement une donnée dans un groupe sans avoir à la déplacer après l’avoir ajouté. Le bouton « Ajouter une donnée » au niveau de la thématique reste affiché et permet de rajouter une donnée en dehors d’un groupe
- [ ] (Facultatif) Le comportement natif permet de supprimer une thématique sans modal de confirmation. Si JDev a le temps, il est demandé si on peut rajouter une modal de confirmation pour valider ou non la suppression d’un thème

Éléments à corriger si reproduits : 

- [ ] Contrôle des couches hors groupe et affichage dans le menu des thématiques -> Non reproduit à ce jour

2024-11-22 08:41 UTC, Gaetanbrl commented
Ta PR est noté en draft @LPoin, est-ce le cas ?

2024-11-22 10:42 UTC, Gaetanbrl commented
@lecault tu peux commencer à tester :)

2024-11-22 14:11 UTC, Gaetanbrl commented
> !!! A merger après https://github.com/mviewer/mviewerstudio/pull/324 !!!

Rebase à prévoir avec branche develop

2024-11-22 16:19 UTC, lecault commented
Premiers retours : 
- Le nom du groupe n'est pas visible dans la carte : 
![image](https://github.com/user-attachments/assets/831ece1b-81f9-405d-9cef-fddb34a7df79)
- J'ai réussi à faire un bug d'affichage via le drap and drop (bug qui fait planter le mviewer car groupe vide)
![image](https://github.com/user-attachments/assets/77a594e0-3c83-41ee-9f65-4ac4f45729d9)

D'ailleurs est-ce un comportement souhaité que mviewer plante si groupe vide ? A première vue, je dirai non.

- J'ai eu des soucis d'affichage dans la TOC de couches hors groupes

- J'ai eu un souci de drag and drop qui rend impossible tout déplacement
![bug_drag_drop](https://github.com/user-attachments/assets/90851629-e109-49eb-8b9f-3e9e29552123)

![bug_drag_drop_2](https://github.com/user-attachments/assets/4cf12d81-acc2-4526-a837-a7c8ce22a7e9)


J'ai remarqué d'autres choses que je mettrai en commun avec @smevel

2024-11-25 07:46 UTC, Gaetanbrl commented
> Le nom du groupe n'est pas visible dans la carte :

En effet, je vois que le group a une propriété title 

`<group id="group-80405619aa6f" title="Nouveau groupe">`

...alors qu'on devrait avoir une propriété name comme ceci :

`<group name="Transport maritime" id="grp2" >`

[Voir cet exemple](https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_topics.html#structure-par-defaut)

> J'ai eu des soucis d'affichage dans la TOC de couches hors groupes
> J'ai eu un souci de drag and drop qui rend impossible tout déplacement

Nous allons vérifier ce comportement

> D'ailleurs est-ce un comportement souhaité que mviewer plante si groupe vide ?

C'est un cas qui sera géré après correction

@LPoin je créer des checkbox dans la description de la PR qui seront à cocher quand ces éléments seront corrigé / vu / validés.

2024-11-25 07:53 UTC, Gaetanbrl commented
> est-ce un comportement souhaité que mviewer plante si groupe vide ? 

Après test, ce comportement provient du mviewer et existait déjà précédemment.
Ce comportement n'est pas souhaitable et est lié à une issue indépendant de cette PR qu'il faut créer et corriger via la communauté.

2024-11-25 08:10 UTC, Gaetanbrl commented
> Ce comportement n'est pas souhaitable et est lié à une issue indépendant de cette PR qu'il faut créer et corriger

Correction disponible dans la branche develop du mviewer.

2024-11-25 11:33 UTC, Gaetanbrl requested changes
1ère phase de revue, des modifications et corrections à apporter :)

2024-11-25 11:33 UTC, Gaetanbrl commented on lib/mv.js
> +              var layer = {
Code redondant, une fonction apporterai plus de lisibilité dans le code

2024-11-25 11:33 UTC, Gaetanbrl commented on js/mviewerstudio.js
> +        config.themes[themeId].groups.find((group) => group.id === groupId).title =
Attribut `title` à remplacer par `name`

2024-11-25 11:33 UTC, Gaetanbrl commented on lib/mv.js
> +            title: $(g).attr("title"),
Propriété `name` à la place de `title`

2024-11-25 11:33 UTC, Gaetanbrl commented on lib/mv.js
> +          addGroup($(th).attr("id"), group.title, group.id);
Propriété `name` à la place de `title`

2024-11-25 11:33 UTC, Gaetanbrl commented on lib/mv.js
> +      const groupTitle = "Nouveau groupe";
I18n utilisable ?

2024-11-25 11:33 UTC, Gaetanbrl commented on lib/mv.js
> +        title: groupTitle,
Propriété `name` à la place de `title`

2024-11-25 11:33 UTC, Gaetanbrl commented on lib/mv.js
> +      const groupTitle = "Nouveau groupe";
Voir ici
https://github.com/mviewer/mviewerstudio/pull/330/files#diff-fbbdf45d15fe208d2883f9619e0098453949e5c3c338cc91532959b79b26554dL498

2024-11-25 11:33 UTC, Gaetanbrl commented on js/mviewerstudio.js
> +            // Cherche l'index de départ en fonction de si le layer bougé vient d'un groupe ou un thème
Attention aux commentaires en FR (anglais à privilégier)

2024-11-25 11:54 UTC, Gaetanbrl commented
Je vois aussi que les infos d'une données ne sont pas chargées dans la modal après avoir fait un drag & drop :

1. Ajouter une thématique
2. Ajouter un groupe
3. Ajouter une données
4. Bouger la donnée dans le groupe
5. Modifier les paramètres de la données
6. Voir que les informations ne sont pas chargées

![image](https://github.com/user-attachments/assets/4222cdd5-15c6-4d03-9612-49696a8eb94a)

2024-11-26 14:31 UTC, lecault commented
Je n'ai pas réussi à reproduire le souci d'affichage de couches en dehors de groupes. Je réessayerai une fois les corrections apportées.

2024-11-29 09:31 UTC, Gaetanbrl commented
@LPoin 
>  La div « Groupes » doit être visible que si on a un ou plusieurs groupe

Je vois toujours la div lors de la création d'un theme : 

https://github.com/jdev-org/mviewerstudio/blob/issue-294/js/mviewerstudio.js#L612

2024-11-29 11:13 UTC, Gaetanbrl commented
> Vérifier / corriger le problème de drag & drop vu dans https://github.com/mviewer/mviewerstudio/pull/330#issuecomment-2494137332 plus bas

Testé, en l'état le D&Drop me convient.

A voir avec @lecault

2024-11-29 11:59 UTC, Gaetanbrl commented
@LPoin a voir pour ce comporte : 

1. ajouter un groupe avec une layer
2. ajouter un autre groupe avec une autre layer (voir image plus bas)
3. modifier l'emplacement de la couche du 2e groupe pour la bouger dans la zone "données" (en dehors d'un groupe)
4. voir que le drag&drop ne fonctionne plus et affiche dans la console cette erreur : 

```
mviewerstudio.js:557 Uncaught TypeError: Cannot read properties of undefined (reading 'layers')
    at jt.onEnd (mviewerstudio.js:557:36)
    at G (Sortable.min.js:2:11483)
    at V (Sortable.min.js:2:12065)
    at jt.\_onDrop (Sortable.min.js:2:29312)
    at jt.handleEvent (Sortable.min.js:2:29659)
```

Code lié en erreur : 

![image](https://github.com/user-attachments/assets/58551cbd-e58b-44d2-8831-74bf9b8c8d19)


Image liée : 

![image](https://github.com/user-attachments/assets/ea2fed67-c97f-417e-a283-cfadabeb6046)

2024-12-02 13:58 UTC, lecault commented
Merci pour les corrections, voici les bugs relevés (trié par ordre d'importance) :

- Quand je clique sur une donnée qui a été "drag and dropée", je ne récupère pas les informations de la donnée :
![image](https://github.com/user-attachments/assets/fa431f5f-ede2-490c-b680-f512f516f1ff)

- Je vois toujours Groupes même s'il y en a pas : 
![image](https://github.com/user-attachments/assets/5c72e457-4748-40f7-b457-0f86fc752728)

- Le nom d'un thème externe importé est éditable et ne devrait pas d'être : 
![image](https://github.com/user-attachments/assets/d3748c66-418a-40b6-8feb-625e93212b82)

- Quand je change l'ordre d'affichage des groupes (via drag and drop), le changement n'est pas (toujours) répercuté dans mviewer

- [mineur] Quelques soucis d'arrondis au niveau des groupes (cela apparait quand on enlève une donnée d'un groupe)
![image](https://github.com/user-attachments/assets/41a054e4-2725-494c-9066-338aea36b949)

J'ai réussi à avoir le souci de drap and drop qui fait planter (mais pas trouvé le scénario). Il suffit de rafraîchir le navigateur pour retrouver le comportement normal.

2024-12-02 14:51 UTC, LPoin commented
Est ce que tu peux vérifier que tu es bien à jour sur la branche ? 
Car les points 
"Quand je clique sur une donnée qui a été "drag and dropée", je ne récupère pas les informations de la donnée"
et 
"Je vois toujours Groupes même s'il y en a pas" 
ont été corrigé et fonctionne correctement chez moi.
On en reparle demain si ça n'est toujours pas ok de votre coté.

2024-12-02 15:32 UTC, lecault commented
Je pense oui car j'ai bien le renommage "Ajouter une thématique" et j'ai bien l'historique des commits : 
![image](https://github.com/user-attachments/assets/fe8b7c81-b41e-4c81-be15-649570c45076)
Et j'ai fait la sychro des fichiers... A demain.

2024-12-02 17:07 UTC, Gaetanbrl commented
Bonjour,
Je viens de récupérer la branche et réinstaller from scratch (via le script d'install .sh) et ces étapes créé un bug (premiere tentative d'utilisation) : 

1. créer une carte
2. créer un theme
3. Ajouter 2 couches
4. Ajouter 2 groupes
5. Affecter une couche par groupe une à une
6. Voir que la seconde couche disparait (le drag and drop "sautille" ou "sacade") et que le drag & drop n'est plus utilisable

![image](https://github.com/user-attachments/assets/e4156bde-97f9-481c-8507-996272bee338)

2024-12-03 16:42 UTC, Gaetanbrl commented
> Je viens de récupérer la branche et réinstaller from scratch (via le script d'install .sh) et ces étapes créé un bug (premiere tentative d'utilisation) :

Testé à l'instant et je ne reproduis **ce bug** plus après réinstallation complète et tests.
Ok pour ce point @LPoin merci pour le correctif.

2024-12-03 16:59 UTC, Gaetanbrl commented
Pour le bug qui concerne l'absence d'information dans la modal des infos de données voici les étapes pour reproduire : 

1. Créer un theme
2. Ajouter un groupe
3. Ajouter une données
4. Déplacer cette donnée vers le groupe
5. Cliquer sur le bouton "éditer la donnée"
6. Voir que la modal s'affiche
7. Voir que les informations de la donnée ne s'affiche pas, la modal est vide en quelque sorte

Analyse technique

Lorsque la méthode `editLayer` (fichier `mviewerstudio.js`) est appelée, il manque l'information sur l'id du groupe.
En l'absence de l'id du groupe, les informations retrouvée ne sont pas correctes et donc, la donnée n'est pas correctement retrouvée pour afficher les informations : 

On voir ici que la layer est `undefined` : 

![image](https://github.com/user-attachments/assets/9ea8941c-cebf-4f5e-bd93-f44985e7dcc6)

2024-12-05 08:48 UTC, lecault commented
C'est bon pour la visualisation de la modal il reste un souci.

Scénario :
- j'ajoute une donnée
- je la déplace dans un groupe
- j'édite cette donnée (ex : changement du titre)
=> la modification n'est pas prise en compte

2024-12-05 09:00 UTC, lecault commented
Autre chose : si on sélectionne l'option réduire le panneau des thématiques au démarrage, le bandeau des thématiques n'est pas réduit.

![image](https://github.com/user-attachments/assets/cd5f5bf5-d220-4f8e-8505-c0a6c8e1d93d)

résultat sur la PR : 

![image](https://github.com/user-attachments/assets/9565e283-4ad2-434d-bbbb-aba0e15905df)

Résultat normal : 

![image](https://github.com/user-attachments/assets/755577bb-d98b-4f5d-b47a-6f7138f9387a)

2024-12-06 13:11 UTC, lecault commented
Lorsque je publie mon application, les groupes ne sont plus visibles dans l'arborescence.

Scénario : 
- Je créé une application
- J'ajoute 3 couches
- Je créé 2 groupes et je mets une des couches dans chaque groupe et une en dehors
- Voici ce que l'on a a l'affichage : 

![image](https://github.com/user-attachments/assets/9cf7e536-0d28-49bc-b743-dd26b8a65565)

- Je publie mon application
- je retourne dans le menu panneau des thématiques
- Voici ce que l'on a a l'affichage, les groupes et leur contenu n'apparaît pas : 

![image](https://github.com/user-attachments/assets/96b3c742-40fb-46eb-80f5-7d46594e9fb5)

Le XML est bon. Pour revoir les groupes, il faut cliquer sur ajouter un groupe et on voit de nouveau les groupes : 

![image](https://github.com/user-attachments/assets/2b715c85-953c-4a16-85c4-b0ddbb9e7ffd)

2024-12-06 13:46 UTC, lecault commented
[territoire.txt](https://github.com/user-attachments/files/18038859/territoire.txt)

Autre souci (moins bloquant), si on importe le XML ci-dessus, on ne voit pas la structure du fichier dans l'arborescence.

Dans la version en développement : 

![image](https://github.com/user-attachments/assets/fb861999-43e7-4c00-9dc8-0d0c07d8ea7e)

Dans l'ancienne version : 

![image](https://github.com/user-attachments/assets/c24c74e1-34bd-4244-9951-b68c14f5aa2f)

2024-12-09 15:42 UTC, lecault commented
Le problème "Lorsque je publie mon application, les groupes ne sont plus visibles dans l'arborescence." est résolu.

2024-12-09 15:45 UTC, lecault commented
Nouveau problème : 

- Je créé une application
- Je mets plusieurs couches / groupes
- Je publie l'application
- Je faire un drag and drop sur les couches, ça bug comme on peut voir dans le gif : 

![freeze_after_publish](https://github.com/user-attachments/assets/c9767365-ee3f-4258-a50b-2d72b362585c)

2024-12-09 17:02 UTC, Gaetanbrl commented
@LPoin je reproduis également avec cette info dans la console :

![Capture d’écran du 2024-12-09 18-02-39](https://github.com/user-attachments/assets/5577365f-7db5-461b-b578-acd184091132)

2024-12-11 08:15 UTC, lecault commented
Merci pour la correction. Je viens de retester mon cas précédent.
C'est un peu mieux mais j'ai toujours des tressautements et si on laisse une couche au milieu, on la perd. Pour reproduire, il suffit de changer l'état de publication d'une application.

![freeze_after_publish_2](https://github.com/user-attachments/assets/778aa76b-c364-4dcf-8764-d652db197cd8)

2024-12-13 07:46 UTC, Gaetanbrl commented
> On se rapproche, plus de souci fonctionnel juste esthétique avec du bleu qui surligne les caractères lorsque l'on déplace une donnée :

OK vue 

Ne concerne que le drag & drop sur le titre. Je ne savais pas que c'était possible, pour moi on utilisait le premier bouton (handler) pour le drag & drop.

A quoi ca sert d'avoir les 2 moyens de drag & drop ? 

@LPoin @lecault

2024-12-16 14:30 UTC, Gaetanbrl commented
> plus de souci fonctionnel juste esthétique avec du bleu qui surligne les caractères lorsque l'on déplace une donnée :

Je viens de pousser un commit suite à un teste avec @Agath21. A voir si ca correspond à ce que tu veux @lecault

2024-12-17 09:08 UTC, lecault commented
Si on modifie l'ordre des groupes dans studio, ce n'est pas répercuté dans mviewer.

Côté studio : 

![image](https://github.com/user-attachments/assets/fcd9b253-1730-4c67-83b6-ad612c34546a)


Côté mviewer : 

![image](https://github.com/user-attachments/assets/3c3eda3b-a75b-4a6f-8bc4-56840672e23b)

2024-12-17 09:23 UTC, Gaetanbrl commented
> Si on modifie l'ordre des groupes dans studio, ce n'est pas répercuté dans mviewer.

Après analyse, je vois que le groupe qui a été bougé est toujours positionné en dernier index du groupe et peu importe sa position dans l'IHM de l'arborescence :

L'IHM : 

![image](https://github.com/user-attachments/assets/133c038d-d628-498a-9333-59e9ead543f0)


Le code lié : 

![image](https://github.com/user-attachments/assets/f685eb3f-8816-4ef9-8c33-c20be87924cc)

2024-12-17 09:40 UTC, LPoin commented
Je viens de regarder, dans mviewerstudio.js ligne 524 dans le onEnd des groupes, ça push dans config.themes[toThemeId].groups mais j'ai oublié d'ajouter la notion d'index comme pour les layers (config.themes[toThemeId].layers.splice(newIndex, 0, itemToMove) )

2024-12-17 09:41 UTC, Gaetanbrl commented
> Je viens de regarder, dans mviewerstudio.js ligne 524 dans le onEnd des groupes, ça push dans config.themes[toThemeId].groups mais j'ai oublié d'ajouter la notion d'index comme pour les layers (config.themes[toThemeId].layers.splice(newIndex, 0, itemToMove) ) Ca push donc toujours à la fin.

Oui c'est corrigé :)

2024-12-17 09:57 UTC, lecault approved these changes
Ok pour moi

2024-12-17 10:13 UTC, Gaetanbrl approved these changes

2024-12-17 10:15 UTC, Gaetanbrl commented
A merger en mode Squash and merge @LPoin :+1:

2024-12-17 10:19 UTC, LPoin commented
Je n'ai pas les droits pour merger moi.

2024-12-17 10:20 UTC, merged

2024-12-17 10:21 UTC, Gaetanbrl commented
La PR est validée, merci à tous pour les développements, suivis et tests.